name: Deploy to EC2

on:
  push:
    branches:
      - main

  #pull_request:
    #branches:
      #- main
    #types: [closed]
  workflow_dispatch:

jobs:
  deployment:
    #if: github.event.pull_request.merged == true
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        #host: ${{ secrets.EC2_HOST_NAME }}
        host: 192.168.2.4
        username: ${{ secrets.EC2_USER_NAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          #ssh -vv ec2-user@192.168.1.26
          cd /myapp
          git pull origin main
